### ISSUE TITLE
Create Bug form on PD Syllabus

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#108]
**Background**
We discussed it would be good for people to be able to raise bugs to us.

**Acceptance criteria**
- Create a bug template on our issues

**Comment by kfklein15** [comment]
Bug form first iteration: https://github.com/CodeYourFuture/PD-curriculum/issues/new/choose

**Comment by LaraHuzjan** [comment]
@kfklein15 Is this still relevant to us? I believe we decided to not have separate forms?

**Comment by kfklein15** [comment]
Yes, closing it :)
