### ISSUE TITLE
Discuss the pilot of the PD Feedback form

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#109]
**Background**
We should start collecting feedback on the new PD Syllabus curriculum and @rogerspooner made this [form](https://github.com/rogerspooner/tusb_hid/issues/new?assignees=&labels=PD&projects=&template=feedback-on-pd-syllabus.yml&title=Feedback+on+XXX) for it. It has been reviewed so now we have to discuss how we'd like to **pilot** this.

**Acceptance criteria**

- [x] how will this work with the bug form
- [x] how would this form be used and when
- [x] how would we go about working on the raised issues
- [x] what would be our broad deadline

**Responsible**
- @CodeYourFuture/pd-syllabus-team 

**Stakeholders**
- @LaraHuzjan 
- @kfklein15 

**Aproover**:
- @kfklein15

**Comment by esma-g** [comment]
Hi all. I cannot make it to the meeting so wanted to share my opinion here:

* I like the feedback form. Maybe it can be a bit shorter.

*** how would this form be used and when**
Is it possible to link the form to the curriculum website?
- If yes, the users can easily view it while working with a certain part of the curriculum.
- If not, I think it would be better to use global-pd-volunteers channel to collect feedback in free text.

*** how would we go about working on the raised issues**
- We can raise tickets on our Kanban board for each feedback
- New tickets are listed in the To Do section
- 1st team member evaluates the feedback and shares their opinion about next steps
- 2nd team member reviews and shares their opinion
- 1st team member finalises their recommendation and moves the ticket to final review
- Following the final review the changes (if any) are implemented in the relevant curriculum page
- 1st team member communicates the changes/decision in the global-pd-volunteers channel and closes the feedback loop

* what would be our broad deadline
- We can aim to resolve each issue in a month.

**Comment by LaraHuzjan** [comment]
@esma-g thanks for this feedback! At yesterday's meeting, we shortened the [form ](https://github.com/CodeYourFuture/PD-curriculum/issues/new/choose) a bit. 

**How would this form be used and when**
The idea was to communicate this to volunteers and add it to canvas. It can also be on the curriculum, although I believe that was done before and not too successful. 

**How would we go about working on the raised issues**
We need to have a chat with Tech Ed about how the raised issues would come directly to us in a ticket form. And then how we would prioritise those tickets and make sure it's not forgotten and lost in the sea of tickets we have. 

I agree with what you wrote, I think this approach works well now as well.
Do you think having a new column for just feedback would make sense?

**What would be our broad deadline**
The idea Karen and I had was to try to resolve an issue in a week-if pressing matter. I'd say max 2 weeks, of course depending on how many tickets we have and how many we can manage. 

@CodeYourFuture/pd-syllabus-team feel free to leave your comments as well

**Comment by esma-g** [comment]
I think a separate column for feedback could work.

About the timing, maybe we can say on Canvas that "We aim to resolve each feedback within 2 weeks. We prioritise urgent issues, such as broken URLs, etc."

**Comment by LaraHuzjan** [comment]
Thanks! I'll bring it up on our weekly meeting and make a post about our work afterward.

**Comment by LaraHuzjan** [comment]
There will be no feedback column, but we'll have a label FEEDBACK. 
There will be no time frame, unless there is an urgent situation.
