### ISSUE TITLE
How to make feedback come directly to us

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#121]
**Background**
We'll soon get more and more feedback. How can we make sure people cn find our form from the Curriculum so it comes directly to us through the [form](https://github.com/CodeYourFuture/PD-curriculum/issues/new/choose) we have. 

**Acceptance criteria**

- [ ] Talk to Tech Ed to define how that could be done - for tickets to be raised directly to us

**Comment by kfklein15** [comment]
You can raise a ticket no the Curriculum board: https://github.com/CodeYourFuture/curriculum/issues

**Comment by LaraHuzjan** [comment]
@kfklein15 I raised the [issue](https://github.com/CodeYourFuture/curriculum/issues/597). Will put it in done
