### ISSUE TITLE
Pilot the PD feedback form

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#133]
**Background**
We, the PD Syllabus team, have discussed our way of working regarding the PD feedback we'll get. Now we need to pilot the [form](https://github.com/rogerspooner/tusb_hid/issues/new?assignees=&labels=PD&projects=&template=feedback-on-pd-syllabus.yml&title=Feedback+on+XXX), so we'll have a designated place for feedback. 

**Acceptance criteria**

- [x] Post the form on Slack
- [x] Include that we'll work on content when we can

**Responsible**
- @LaraHuzjan 
- @kfklein15 

**Stakeholders**
- @LaraHuzjan 
- @kfklein15 

**Aproover**:
- @kfklein15

**Comment by kfklein15** [comment]
I have shared the link with WM5

**Comment by LaraHuzjan** [comment]
Posted on NW6 general, WM5 general and global pd volunteers.
