### ISSUE TITLE
Node/S2 - Difficult workplace conversation

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#24]
**Class Prep (1 hour)**
1. Read the theory on the topic of difficult workplace situations                    
2. Watch the [video](https://www.ted.com/talks/amy_cuddy_your_body_language_may_shape_who_you_are/c) on Body language 

**Class Exercises (1 hour)**
Conflict resolution

**Coursework Content (180 minutes)**
- How will AI impact tech (1,000 words). Share the document (on the text!) on a channel. 
- Read someone else's text (someone you don't know that well in your cohort) and give feedback on it.
- Practice interview using software XYZ

**Reference Materials**
https://syllabus.codeyourfuture.io/node/week-2/lesson#pd-diversity-and-inclusion
https://docs.google.com/document/d/1HM-02_m66qqeEMfN0K6tBu-eIqs81WB35Id2vQBcDrw/edit

[**Link to Google Doc**](https://docs.google.com/document/d/1QT0ugfDnpiyjSkyZHrpTTBzJkR_Oc-AGYsbEnSrYy2w/edit?usp=sharing)

CONTACT BARNEY

**Comment by LaraHuzjan** [comment]
New [PR](https://github.com/CodeYourFuture/curriculum/pull/574) for Prep
