### ISSUE TITLE
Node/S3 - Value and Work not done

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#25]
**Class Prep (1 hour)**
Research about Work not done + incremental work + INVEST

**Ideas for Class Exercises (1 hour)**
Game of work not done / incremental delivery

**Ideas for Coursework (180 minutes)**
Write a short text with the top 3 tips you learned so far about interview
Review your development plan

**Reference Materials**

[Link to Google Doc](https://docs.google.com/document/d/14yZ19nU0z0GiXq-l4qIfOmJ2sQUzjzNYGAEgH1r4UiQ/edit)  -----> the new/right link. Review this one

**Comment by LaraHuzjan** [comment]
New [Prep PR](https://github.com/CodeYourFuture/curriculum/pull/576)
