### ISSUE TITLE
Node/S4 - Sell yourself

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#26]
**Class Prep (1 hour)**
Do a mock interview with your peer using Evidenced. 
Watch the recording and think about 2 examples in which you sold yourself well and why. 
And 2 examples in which you didn't sell yourself well and why.

**Class Exercises (1 hour)**
Sell yourself exercise: ?

Sell yourself tips: what do you need to know to sell yourself? What can you prepare? Gather 5 tips. > this should be them pitching themselves

2. Spreadsheet for the group work (4 people per group for the next module). Who can set it up so this can be done asynchronously?

**Coursework (180 minutes)**
1. Do another mock-up interview based on your learnings using Evidenced between trainees. Watch your recording, and write a reflection (what went well/not so well) of minimum 100 words, share on the main channel

2. Define actions from your own feedback and from the interviewer, update your personal development plan. Share these actions.

3. Practice interviews and seeling yourself with ChatGPT

**Reference Materials**
https://module-graduates.codeyourfuture.io/further-activities/collective-job-search
https://syllabus.codeyourfuture.io/db/week-2/lesson#pd-learning-to-sell-yourself

[**Link to Google Doc**](https://docs.google.com/document/d/10uW7xlwfp1sfvEYprBwORiveM9-UXbhoApQDPpef7Vs/edit)

**Comment by LaraHuzjan** [comment]
New [Day Plan PR](https://github.com/CodeYourFuture/curriculum/pull/577)
