### ISSUE TITLE
SQL/S2 - JD + Questions for employers

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#28]
**Class Prep (1 hour)**
1. Find 1 job application and understand it: what type of company is it, what type of job, which skills you match directly, and indirectly which ones you don't.
2. Think about questions you would ask
3. Think about what are the needs and pain points of the company and this company (understand:headcount, for example

**Class Exercises (1 hour)**
1. Discuss what you identified on your JD and give feedback on each other's work.
2. What kind of questions would you ask this employer before the interview or during the interview? What should you not ask?
3. Discuss needs and pain points of employers and how we can use this to start conversations/ask questions?
4. Follow-up after the interview

**Coursework (180 minutes)**
1. In your group, each of you must find 1 job applications and understand them: what type of company is it, what type of job, which skills you match directly, and indirectly (transferrable skills), which ones you don't. Discuss what you identified and give feedback on each other's work. (1 h)
2. Proctive using chat GPT with this JD you identfiied
3. Pre-FP work"
4. Review your Development Plan

**Reference Materials**
https://syllabus.codeyourfuture.io/db/week-2/lesson#pd-learning-to-sell-yourself

[**Link to Google Doc**](https://docs.google.com/document/d/1W8jkrSQ7IDB_JKolVhB-YpWUo8gB9iffu5vDJnbEgEQ/edit)

ASK BARNEY FOR GUIDANCE

**Comment by LaraHuzjan** [comment]
New [Prep PR](https://github.com/CodeYourFuture/curriculum/pull/578)
