### ISSUE TITLE
Induction-Module success

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#51]
For clarity purposes and a better overview of the cohort's ability to move to the next module, there will be a simplified module success assessment. The existing one is not that useful.
- There will be 5 items that have to be done for the module to be complete and therefore the cohort to move to the next one.
- 3 will be tech-related and 1-2 PD-related per module.
- Example of a Tech one: 70% of the cohort is at or beyond milestones.

**Comment by LaraHuzjan** [comment]
@kfk do we upload the succes to Sprint one? There is another success block meant for the entire module I believe?

**Comment by kfklein15** [comment]
Module success is in the "Success" file. Example of path from DB: org-cyf/content/databases/success
