### ISSUE TITLE
React-Module success and LOs

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#54]
For clarity purposes and a better overview of the cohort's ability to move to the next module, there will be a simplified module success assessment. The existing one is not that useful.
- There will be 5 items that have to be done for the module to be complete and therefore the cohort to move to the next one.
- 3 will be tech-related and 1-2 PD-related per module.
- Example of a Tech one: 70% of the cohort is at or beyond milestones.

Additionally, please look at the learning objectives used in this entire module and please improve them using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Acceptance criteria**

- [x] Upload LOs
- [x] Upload Module success

**Comment by LaraHuzjan** [comment]
Perfect, thanks :) @kfklein15 these are ready for your final review

Learning Objectives:

Sprint 1
Current:
Reflect on embracing failure as part of growth
Explore your current resilience and how you can improve it

Revised:
(Prep) Explain how failure can be part of growth
(Class) Describe 2 methods to improve resilience

Sprint 2
Current:
Describe each of the problem solving approaches in max 3 sentences.
Generate at least 10 brainstorming ideas during the exercise
Identify at least 3 examples for each step/letter of the IDEA approach for solving problems

Revised:
(Prep) Describe 3 problem solving methods
(Class) List 3 requirements for an effective brainstorming session
(Class) Apply IDEA approach to solve a problem

Sprint 3
Current:
Describe three methods of increasing the value of work delivered by a team
Describe the benefit of getting early customer feedback.
In max 5 sentences explain how you would assess whether a certain task is a priority or not.

Revised:
(Prep) Describe 3 methods to increase the value of work
(Class) Explain the benefit of getting early customer feedback
(Class) Decide whether a task is a priority at a given time or not

Sprint 4
Current:
Define concepts related to diversity and inclusion
Explain three situations where a tech product can be inaccessible
Explain feelings associated with being included or excluded in five sentences
Describe at least two coping methods against social exclusion
Prepare a brief for an inclusive tech product

Revised:
(Prep) Explain 3 situations where a tech product is inaccessible
(Class) Identify 2 coping methods against social exclusion
(Class) Prepare a brief for an inclusive tech product

Module Success:

Trainees have written at least one cover letter for a job application and received feedback for it
Trainees added at least one new goal to their development plan using SMART goal setting framework
Trainees prepared a brief for an accessible and inclusive tech product

**Comment by kfklein15** [comment]
Learning objectives are looking great! Well done!

For Success criteria, I would go with these two. I added the 100%, but happy if you think it should be 80% or 90%.
- 100% of the trainees have written at least one cover letter for a job application and received feedback for it
- 100% of the trainees prepared a brief for an accessible and inclusive tech product

**Comment by LaraHuzjan** [comment]
[PR Module success](https://github.com/CodeYourFuture/curriculum/pull/582)

**Comment by LaraHuzjan** [comment]
@esma-g I'll start uploading the LOs now :)

**Comment by LaraHuzjan** [comment]
MO are live as well, so I'll close the ticket
