### ISSUE TITLE
Final project/Launch Project-Module success

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#57]
For clarity purposes and a better overview of the cohort's ability to move to the next module, there will be a simplified module success assessment. The existing one is not that useful.
- There will be 5 items that have to be done for the module to be complete and therefore the cohort to move to the next one.
- 3 will be tech-related and 1-2 PD-related per module.
- Example of a Tech one: 70% of the cohort is at or beyond milestones.

Additionally, please look at the learning objectives used in this entire module and please improve them using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Comment by kfklein15** [comment]
My suggestion for Module success:

Trainee has achieved the individual, project criteria and team criteria described in the [Exit Launch document](https://docs.google.com/document/d/1eS6sYRP8Jw-siL_cqA-ql_13XWbWhMJlTx9d0H4b47A/edit#heading=h.dy5up1lc4fq)

**Comment by LaraHuzjan** [comment]
I think it's good

**Comment by kfklein15** [comment]
[PR raised.](https://github.com/CodeYourFuture/curriculum/pull/630) It's not passing checks
