### ISSUE TITLE
Read all published content to ensure it is clear and achieving the goals

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/PD-curriculum#71]
**Read all final content to identify:**
- Any repetition of content
- PD and Tech Ed content making sense and aligned
- Ensure it's clear WHY people have to read a text or watch a video (maybe write down some points)
- Anything important missing

**Outcome**
- Raise a list/doc of possible changes per module
- Discuss it with the team
- Define the ones that should have tickets raised on our PD Backlog

**Comment by LaraHuzjan** [comment]
Use this [tech curriculum overview](https://curriculum.codeyourfuture.io/overview/) to compare

**Comment by LaraHuzjan** [comment]
Has been broken down in smaller tickets
