### ISSUE TITLE
Induction-Learning Objectives

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#86]
Improve the quality of previous Learning Objectives using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Comment by esma-g** [comment]
Learning Objectives:

Sprint 1
Current:

Revised:
(Prep) 
(Class) 

Sprint 2
Current:

Revised:
(Prep) 
(Class) 

Sprint 3
Current:

Revised:
(Prep) 
(Class) 

Sprint 4
Current:

Revised:
(Prep) 
(Class)

**Comment by LaraHuzjan** [comment]
Thanks @esma-g, I just added the two words, just so it easier to measure. :) @kfklein15 these are ready to be reviewed. 

Sprint 1
Current:
Describe the goals of the Software Development course and what is expected of you
Describe how we learn as a community at CYF
Describe a typical week at Code Your Future
Detail your availability on a shared spreadsheet
Divide the group in pairs considering people's availability using Google sheet

Revised:
(Class) List the milestones for the Software Development Course
(Class) Identify 3 ground rules for effective community learning
(Class) Share availability with others **using a spreadsheet**
(Class) Organise pairs for co-working **using Google sheet**

**Comment by kfklein15** [comment]
Looks good to me. I think you just have to update them on the CMS, right?

**Comment by LaraHuzjan** [comment]
@esma-g @kfklein15 I've uploaded 1,3,4 LO. Not sure [Learning as a community](https://cyf-curriculum.netlify.app/induction/sprints/1/day-plan/) is part of PD as I can't find it on CMS?

**Comment by esma-g** [comment]
1. I don't think updating CMS is enough. I updated them on Friday but [the website](https://cyf-curriculum.netlify.app/induction/sprints/1/day-plan/#welcome-to-code-your-future) still shows old learning objectives.
2. I also couldn't find "Identify pairs per week" in the CMS. I thought it was PR content.
3. Learning as a community seems to be Tech Edu content, see [issue link with comment](https://github.com/CodeYourFuture/curriculum/issues/1118).

**Comment by LaraHuzjan** [comment]
1. did you update these? I didn't know you were doing that as well. Can we next time let each other know so we don't repeat the work :) 
2. I updated those - the link that you sent is showing me the right LOs
3. Ok so LO nr2 isn't relevant for us. Thanks

**Comment by LaraHuzjan** [comment]
I've updated this on the CMS and it's live.

**Comment by esma-g** [comment]
1. It was assigned to me, that is why I was working on it.

Thanks for sorting it!

**Comment by LaraHuzjan** [comment]
No problem, I should have said I was doing it as well :)
