### ISSUE TITLE
Node(Servers)-Learning Objectives and Module success (yet to be done)

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#87]
Improve the quality of previous Learning Objectives using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy
- 
**Acceptance criteria**

- [x] Upload LOs
- [x] Upload Module success

**Comment by kfklein15** [comment]
Absolutely fantastic work, @wainwmr  Thanks!

**Comment by LaraHuzjan** [comment]
@kfklein15 these LOs have been uploaded. Module success not yet. Hence why it's still in this column. I'll do that tomorrow and then move it.
Just fyi Servers S2 and S3 day plan-there is still just the pd placeholder, no content. Not sure how since we checked this last week and the only issue was Prep. I'll look into it tomorrow.

**Comment by LaraHuzjan** [comment]
Module success [PR](https://github.com/CodeYourFuture/curriculum/pull/590) 

Everything has been uploaded, waiting to see if it'll be live.

**Comment by LaraHuzjan** [comment]
Everything is live

**Comment by kfklein15** [comment]
Merged
