### ISSUE TITLE
HTML/CSS-Learning Objectives

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#90]
Improve the quality of previous Learning Objectives using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Comment by esma-g** [comment]
Learning Objectives:

Sprint 1
Current:

Revised:
(Prep) 
(Class) 

Sprint 2
Current:

Revised:
(Prep) 
(Class) 

Sprint 3
Current:

Revised:
(Prep) 
(Class) 

Sprint 4
Current:

Revised:
(Prep) 
(Class)

**Comment by esma-g** [comment]
@LaraHuzjan I'm suggesting to use only the revised ones. I added the current ones for comparison.

**Comment by LaraHuzjan** [comment]
Ok perfect, thanks :) @kfklein15 the ones in the comment done by me are ready for review.
