### ISSUE TITLE
JS1-Learning Objectives

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#91]
Improve the quality of previous Learning Objectives using this [PD LO workpad google doc](https://docs.google.com/document/d/1vL7spdtwf8GnrwEioh5RUoqqGKkcF-vh0DfXkhURCBc/edit#heading=h.wo6oehvrqfxg)

- Begin with an active verb
- Testable
- Use Bloom's taxonomy

**Comment by kfklein15** [comment]
Hi @rogerspooner , have you started working on this?

**Comment by kfklein15** [comment]
Ignore me, this has been done, but we can't find the ticket. :)
