### ISSUE TITLE
PD onboarding: define approach after cohort founders check-in

### ISSUE THREAD

**Issue by LaraHuzjan** [CodeYourFuture/PD-curriculum#92]
**Background**
The system we had so far was inefficient, so we need a new way of onboarding new PD volunteers and have recurring meetings. 
PD Volunteers are not onboarded properly and are therefore doing things their own way. There needs to be an intro to flipped classrooms and explaining what they are and what is expected of them.

**Acceptance criteria**

- [x] Chat with cohort founders
- [ ] Propose a new approach based on the info
- [ ] Raise necessary tickets

**Comment by LaraHuzjan** [comment]
Hey @Dedekind561. I was talking to Karen and she mentioned you were doing something similar for trainees and tech volunteers. Were you thinking of like a communal intro to flipped classrooms with trainees and all volunteers or? Just curious to see what you are doing so we know what our next steps can be as PD V are still passively lecturing and using their own content...

**Comment by Dedekind561** [comment]
Hi @LaraHuzjan, 
I'm currently thinking about the next steps to take with this problem -  it is a challenge with tech-ed volunteers too. It would be helpful to discuss your challenges in person so I can get more context on the problem. Do you have any availability to catchup some this week?

But here are my current thoughts:
- Cohort founder training workshop
- I think a communal intro to flipped classroom with all trainees and volunteers is a good idea: there are some workshops in Fundamentals, but they need to be updated. 
- I think that the whole of Fundamentals needs to be updated so it also works more like a training course for new volunteers and trainees

**Comment by LaraHuzjan** [comment]
It'd be great to talk yes. This week I could only meet tomorrow anytime from 10-11.30. If not, please have a look at my calendar and book whenever works best for you. I see you have a lot going on.

**Comment by kfklein15** [comment]
This will be part of the milestone https://github.com/CodeYourFuture/Programme/issues/30 , which we will have to break down. Add a meeting with @Dedekind561 and @LaraHuzjan
